package com.example.zzj.geendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.zzj.entity.media;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEDIA".
*/
public class mediaDao extends AbstractDao<media, Long> {

    public static final String TABLENAME = "MEDIA";

    /**
     * Properties of entity media.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Med_id = new Property(0, Long.class, "med_id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Type = new Property(2, int.class, "type", false, "TYPE");
        public final static Property Note = new Property(3, String.class, "note", false, "NOTE");
    };


    public mediaDao(DaoConfig config) {
        super(config);
    }
    
    public mediaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEDIA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: med_id
                "\"NAME\" TEXT," + // 1: name
                "\"TYPE\" INTEGER NOT NULL ," + // 2: type
                "\"NOTE\" TEXT);"); // 3: note
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEDIA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, media entity) {
        stmt.clearBindings();
 
        Long med_id = entity.getMed_id();
        if (med_id != null) {
            stmt.bindLong(1, med_id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getType());
 
        String note = entity.getNote();
        if (note != null) {
            stmt.bindString(4, note);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, media entity) {
        stmt.clearBindings();
 
        Long med_id = entity.getMed_id();
        if (med_id != null) {
            stmt.bindLong(1, med_id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getType());
 
        String note = entity.getNote();
        if (note != null) {
            stmt.bindString(4, note);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public media readEntity(Cursor cursor, int offset) {
        media entity = new media( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // med_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.getInt(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // note
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, media entity, int offset) {
        entity.setMed_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setType(cursor.getInt(offset + 2));
        entity.setNote(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(media entity, long rowId) {
        entity.setMed_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(media entity) {
        if(entity != null) {
            return entity.getMed_id();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
